# Site settings
title: alican
email: alishex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alican\'s blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alican.co" # the base hostname & protocol for your site
twitter_username: AlicanHasirci
github_username:  AlicanHasirci

# Build settings
markdown: kramdown
