# Site settings
description: alican.co
title: alican.co
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alican.co" # the base hostname & protocol for your site

# User settings
username: Alican HASIRCI
user_description: Developer at Peak Games
user_title: Developer at Peak Games
email: alican@peakgames.net
twitter_username: AlicanHasirci
github_username:  AlicanHasirci
gplus_username:  AlicanHasirci
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
